# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 23:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workers', '0002_auto_20160225_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_inkjet_1', models.IntegerField(default=0)),
                ('qty_inkjet_2', models.IntegerField(default=0)),
                ('qty_laser_1', models.IntegerField(default=0)),
                ('qty_laser_2', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Comments')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.Stores', unique_for_date='date')),
                ('workers', models.ManyToManyField(to='workers.Workers')),
            ],
        ),
    ]
