# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20160316_2250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reports',
            unique_together=set([('store', 'date')]),
        ),
    ]
