# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 23:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=30, verbose_name='prénom')),
                ('lastname', models.CharField(default='', max_length=30, verbose_name='nom de famille')),
                ('corporate_name', models.CharField(default='', max_length=60, verbose_name='raison sociale')),
                ('professional', models.BooleanField(default=False, verbose_name='professionnel')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_1', models.CharField(default='', max_length=10, verbose_name='téléphone #1')),
                ('phone_2', models.CharField(default='', max_length=10, verbose_name='téléphone #2')),
                ('address', models.CharField(default='', max_length=60, verbose_name='adresse')),
                ('zipcode', models.CharField(default='', max_length=6, verbose_name='code postal')),
                ('town', models.CharField(default='', max_length=20, verbose_name='ville')),
                ('country', models.CharField(default='', max_length=20, verbose_name='pays')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.Stores', verbose_name='magasin')),
            ],
        ),
    ]
