# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterUniqueTogether(
            name='customers',
            unique_together=set([('firstname', 'lastname', 'store')]),
        ),
    ]
