# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20160316_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='lastname',
            field=models.CharField(max_length=30, verbose_name='nom de famille'),
        ),
        migrations.AlterUniqueTogether(
            name='customers',
            unique_together=set([]),
        ),
    ]
