# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20160315_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstores',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='fullname',
            field=models.CharField(max_length=30, verbose_name='nom complet'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.GroupStores', verbose_name='groupe'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='workers',
            field=models.ManyToManyField(to='workers.Workers', verbose_name='employé(s)'),
        ),
    ]
