# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20160225_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplaces',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='workplaces',
            name='short',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
