# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20160315_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='workplace',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='workers.Workplaces', verbose_name='poste'),
        ),
        migrations.AlterField(
            model_name='workplaces',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='workplaces',
            name='short',
            field=models.CharField(max_length=3, unique=True, verbose_name='nom court'),
        ),
    ]
